### PR TITLE
Enable Bundle-Autoconfig by Flex

### PR DESCRIPTION
**Pull request by chr-hertel**
to enable flex' autoconfiguration of this bundle we need to switch to symfony compliant class names

### CODE REVIEW

**Comment by nunomaduro** [comment]
Thanks @chr-hertel. I am gonna merge this and tag it tonight.

**Comment by dbrumann** [comment]
Thanks for looking into this :+1:

**Comment by xabbuh** [comment]
it looks like the tests need to be updated to

**Comment by nunomaduro** [comment]
@xabbuh Yeah. We need to update tests before merged this PR.

**Comment by chr-hertel** [comment]
@xabbuh @nunomaduro should be fine now, thanks 👍

**Review by dbrumann — APPROVED** [review]

**Review by xabbuh — APPROVED** [review]

**Comment by nunomaduro** [comment]
Thanks @chr-hertel !

**Pull request merged**
